# Generated by Django 2.1.5 on 2019-03-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='norsk',
            field=models.BooleanField(default=False),
        ),
    ]
