# Generated by Django 2.1.5 on 2019-02-12 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discussions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField()),
                ('has_experience', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')])),
                ('experience', models.TextField()),
                ('experience_helpful', models.TextField()),
                ('factors', models.TextField()),
                ('emotions', models.TextField()),
                ('solutions', models.TextField()),
                ('learnings', models.TextField()),
                ('current', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')])),
                ('readability', models.TextField()),
                ('wordFrequency', models.TextField(default='')),
                ('sentiment', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('tags', models.CharField(default='', max_length=255)),
                ('is_group', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reflections', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_reflections', to='projects.Group')),
            ],
        ),
        migrations.AddField(
            model_name='prompts',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_prompts', to='reflections.Reflection'),
        ),
        migrations.AddField(
            model_name='prompts',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_discussions', to='reflections.Reflection'),
        ),
    ]
