# Generated by Django 2.1.5 on 2019-02-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_auto_20190220_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='reflection',
        ),
        migrations.AddField(
            model_name='reflection',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
