# Generated by Django 2.1.5 on 2019-02-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0003_auto_20190220_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='experience_feedback',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='discussion',
            name='learning_feedback',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='discussion',
            name='reflection_feedback',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='experience_helpful',
            field=models.TextField(blank=True),
        ),
    ]
