# Generated by Django 2.1.5 on 2019-02-27 11:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reflections', '0004_auto_20190222_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompts',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='prompts',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='reflection',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reflection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reflections_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
