# Generated by Django 2.1.5 on 2019-02-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0006_auto_20190227_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='reflection',
            field=models.ManyToManyField(related_name='reflection_tags', to='reflections.Reflection'),
        ),
    ]
