# Generated by Django 2.1.5 on 2019-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0007_auto_20190227_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='actions',
            field=models.TextField(default=''),
        ),
    ]
